<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="author" content="陈俊如">
        <title>宝钢首页</title>
        <link rel="stylesheet" href="style.css">
        <meta name="viewport" content="initial-scale=1,maximum-scale=1,minimum-scale=1">
        <style></style>
    </head>
    <body>
<header>
            <div class="navbar">
                <img src="logo.png" alt="">
                <ul>
                <li><a href="">首页</a></li>
                <li><a href="">媒体中心</a></li>
                <li><a href="">关于我们</a></li>
                <li><a href="">产品服务</a></li>
                <li><a href="">业务板块</a></li>
            </ul>
            </div>
        </header>